#!/bin/bash

PGPASSWORD=$POSTGRES_PASSWORD psql -v --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
  CREATE DATABASE $DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
EOSQL
